"""add is_complete to libros

Revision ID: 681164b10f13
Revises: da51b22f1963
Create Date: 2026-10-06 14:11:35.305578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681164b10f13'
down_revision = 'da51b22f1963'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_complete', sa.Boolean(), nullable=False, server_default=sa.true()))
    
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.alter_column('is_complete', existing_type=sa.Boolean(), server_default=None)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
