"""Esquema inicial de la db con los modelos de: Usuario, Rol, Biblioteca, Asignacion, Libro, Editorial, Autor, Estado, Ejemplar y la tabla intermedia libro_autor

Revision ID: 9bc8215d841e
Revises: 
Create Date: 2026-09-14 20:01:59.496806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc8215d841e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('bibliotecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editoriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=70), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('username')
    )
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('biblioteca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['biblioteca_id'], ['bibliotecas.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'biblioteca_id', name='uq_usuario_biblioteca')
    )
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year_publication', sa.Integer(), nullable=True),
    sa.Column('clasificacion', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['editorial_id'], ['editoriales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('ejemplares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('biblioteca_id', sa.Integer(), nullable=False),
    sa.Column('signatura', sa.String(length=100), nullable=True),
    sa.Column('numero_ejemplar', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['biblioteca_id'], ['bibliotecas.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libro_id', 'numero_ejemplar', name='uq_libro_numero_ejemplar')
    )
    op.create_table('libro_autor',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'autor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libro_autor')
    op.drop_table('ejemplares')
    op.drop_table('libros')
    op.drop_table('asignaciones')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('estados')
    op.drop_table('editoriales')
    op.drop_table('bibliotecas')
    op.drop_table('autores')
    # ### end Alembic commands ###
