"""add library fields and is_owner to asignacion

Revision ID: ce2453c66df5
Revises: 56e7f75c1e48
Create Date: 2026-09-25 21:43:02.987283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2453c66df5'
down_revision = '56e7f75c1e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.Boolean(), nullable=False))

    with op.batch_alter_table('bibliotecas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliotecas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.drop_column('is_owner')

    # ### end Alembic commands ###
