"""change unique constraint on ejemplares to include biblioteca_id

Revision ID: d59e75a3ee75
Revises: ce2453c66df5
Create Date: 2026-10-01 14:39:58.407564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59e75a3ee75'
down_revision = 'ce2453c66df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejemplares', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_libro_numero_ejemplar'), type_='unique')
        batch_op.create_unique_constraint('uq_libro_biblioteca_numero', ['libro_id', 'biblioteca_id', 'numero_ejemplar'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejemplares', schema=None) as batch_op:
        batch_op.drop_constraint('uq_libro_biblioteca_numero', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_libro_numero_ejemplar'), ['libro_id', 'numero_ejemplar'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
